# Generated by Django 5.2.13 on 2026-10-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notification_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Попыток уведомления"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notification_last_attempt_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя попытка уведомления"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notification_last_error_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Код последней ошибки уведомления",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Уведомление принято почтовым backend",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестно"),
                    ("pending", "Ожидает отправки"),
                    ("sending", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Состояние уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестно"),
                    ("pending", "Ожидает отправки"),
                    ("sending", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Состояние уведомления",
            ),
        ),
    ]
