# Generated by Django 5.2.13 on 2026-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_notification_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="submission_fingerprint",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="Отпечаток отправки",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="submission_id",
            field=models.UUIDField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Идентификатор отправки",
            ),
        ),
    ]
