# Generated by Django 5.2.13 on 2026-10-01 14:42

import apps.leads.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_submission_fingerprint_lead_submission_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.leads.models.private_lead_attachment_storage,
                        upload_to="leads/attachments/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Исходное имя"),
                ),
                ("size", models.PositiveBigIntegerField(verbose_name="Размер")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="leads.lead",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение заявки",
                "verbose_name_plural": "Вложения заявки",
                "ordering": ("id",),
            },
        ),
    ]
