# Generated by Django 5.2.13 on 2026-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_leadattachment_legacy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign_attribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='Рекламный источник'),
        ),
        migrations.AddField(
            model_name='lead',
            name='direction_slug',
            field=models.CharField(blank=True, max_length=40, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='lead',
            name='direction_type',
            field=models.CharField(blank=True, choices=[('product', 'Продукт'), ('service', 'Услуга')], max_length=10, verbose_name='Тип направления'),
        ),
    ]
