# Generated by Django 5.2.13 on 2026-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_system',
            field=models.CharField(db_index=True, default='td_site', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('rejected', 'Rejected'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
